PATCH http://localhost:8090/mixer/new
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzc4MDM5NzMsInVzZXJuYW1lIjoieWFsZGEifQ.22zcfSPLOPyTqj_OLh6g3JMpALDBeSBcqG0EqIoj7sw

{
    "id": 2,
    "name" : "mud",
    "price": 150,
    "mix_time": 99
}