PATCH http://localhost:8090/mixer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzc3MDcxOTgsInVzZXJuYW1lIjoiYWxhcm5pbmphZCJ9.3FvqQxejw6i7WVPzS06WEQJaUmH9abifjd06VsNwiVg

{
    "id": 1
}