PATCH http://localhost:8090/mixer/new
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzc3MDc2NjcsInVzZXJuYW1lIjoiYWxhcm5pbmphZCJ9.__NSwowOKvbTnbs3R_LQHw6ycBTHNAd5NkMPe1Uq_fY

{
    "id": 1,
    "name" : "ass",
    "price": 1,
    "mix_time": 10
}