PATCH http://localhost:8090/mixer/new
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzgxNTM2NzAsInVzZXJuYW1lIjoibWVvdyJ9.sA7x5e-zHQuvGOf7e6WrpRLDEomqE3R21ovmg6-EqgQ

{
    "id": 1,
    "name" : "the new element of the universe",
    "price": 1500,
    "mix_time": 99
}