POST http://localhost:8090/shop/buy
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzgwNzEyNDYsInVzZXJuYW1lIjoiMSJ9.OoO4H4tGzgVNl8eIQiCfO2qBl_Vd_VgO5cl3GIsB3oo

{
    "seller_username": "admin",
    "material_name": "water",
    "number": 1,
    "price": 5
}