POST http://localhost:8090/mixer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzY2NzMyNTgsInVzZXJuYW1lIjoiYWxhcm5pbmphZCJ9.KP9FKT40dUVfRXWUkdfoEBB-ElMyvllTOviWrdttFOE

{
    "first_ingredient_name": "weed_seed",
    "second_ingredient_name": "dirt",
    "number": 1
}