POST http://localhost:8090/mixer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzc4MDM3MzMsInVzZXJuYW1lIjoieWFsZGEifQ.OO9Hhxr6UMZY5ARb-_c1Mm7pWGo5Xyn2VHN-uQvfkYc

{
    "first_ingredient_name": "water",
    "second_ingredient_name": "mude",
    "number": 1
}