POST http://localhost:8090/shop
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzc3MDk1ODgsInVzZXJuYW1lIjoiYWxhcm5pbmphZCJ9.NhvfIIH_n4mhrc3ZiLxprBIJhA5aLey-_tvTG-ecWVI

{
    "material_name": "ass",
    "number": 1,
    "price": 99
}